[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = true
# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
# You could also set a static color if you use the color keywords and the wallpaper setter supports it.
command = "pkill swaybg && swaybg -i {{ image }} -m fill &"

[templates.mango]
input_path = '~/.config/matugen/templates/mango-colors.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Colors.conf'
post_hook = "kitty +kitten themes --reload-in=all Colors"

[templates.btop]
input_path = '~/.config/matugen/templates/btop-colors.theme'
output_path = '~/.config/btop/themes/colors.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3.css'
output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.foot]
input_path = '~/.config/matugen/templates/foot-colors.ini'
output_path = '~/.config/foot/colors.ini'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim-colors.lua'
output_path = '~/.config/nvim/lua/plugins/theme.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.helix]
input_path = '~/.config/matugen/templates/helix-colors.toml'
output_path = '~/.config/helix/themes/colors.toml'

[templates.swaylock]
input_path = '~/.config/matugen/templates/swaylock-colors'
output_path = '~/.config/swaylock/config'
