general {
    lock_cmd = pidof swaylock || swaylock
    before_sleep_cmd = swaylock
    after_sleep_cmd = mmsg dispatch enable_monitor,
}

listener {
    timeout = 120
    on-timeout = swaylock
}

listener {
    timeout = 120
    on-timeout = mmsg dispatch disable_monitor,
    on-resume = mmsg dispatch enable_monitor,
}

listener {
    timeout = 120
    on-timeout = brightnessctl -sd kbd_backlight set 0
    on-resume = brightnessctl -rd kbd_backlight
}

listener {
    timeout = 180
    on-timeout = systemctl suspend
}
