general {
    lock_cmd = swaylock
    before_sleep_cmd = swaylock
    after_sleep_cmd = niri msg action power-on-monitors
}

listener {
    timeout = 120
    on-timeout = swaylock
}

listener {
    timeout = 120
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

listener {
    timeout = 120
    on-timeout = brightnessctl -sd kbd_backlight set 0
    on-resume = brightnessctl -rd kbd_backlight
}

listener {
    timeout = 180
    on-timeout = systemctl suspend
}
