# Matugen Foot Template

[colors-dark]
alpha=1.0
background=121318
foreground=e2e2e9
regular0=121318
regular1=ffb4ab
regular2=b2c5ff
regular3=e1bbdd
regular4=dae2ff
regular5=dce2f9
regular6=c0c6dd
regular7=e2e2e9
bright0=38393f
bright1=ffb4ab
bright2=b2c5ff
bright3=e1bbdd
bright4=dae2ff
bright5=dce2f9
bright6=c0c6dd
bright7=e2e2e9
selection-foreground=b2c5ff
selection-background=172e60
cursor=45464f e2e2e9

[colors-light]
alpha=1.0
background=121318
foreground=e2e2e9
regular0=121318
regular1=ffb4ab
regular2=b2c5ff
regular3=e1bbdd
regular4=dae2ff
regular5=dce2f9
regular6=c0c6dd
regular7=e2e2e9
bright0=38393f
bright1=ffb4ab
bright2=b2c5ff
bright3=e1bbdd
bright4=dae2ff
bright5=dce2f9
bright6=c0c6dd
bright7=e2e2e9
selection-foreground=b2c5ff
selection-background=172e60
cursor=45464f e2e2e9
