general {
    lock_cmd = swaylock
    before_sleep_cmd = swaylock
    after_sleep_cmd = mmsg -d enable_monitor
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = brightnessctl -sd kbd_backlight set 0
    on-resume = brightnessctl -rd kbd_backlight
}

listener {
    timeout = 180
    on-timeout = swaylock
}

listener {
    timeout = 180
    on-timeout = mmsg -d disable_monitor
    on-resume = mmsg -d enable_monitor && brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
