color0 #0f1416
color1 #ffb4ab
color2 #88d1ec
color3 #b3cad4
color4 #c3c3eb
color5 #88d1ec
color6 #b3cad4
color7 #dee3e6
color8 #8a9296
color9 #ffb4ab
color10 #88d1ec
color11 #b3cad4
color12 #c3c3eb
color13 #88d1ec
color14 #b3cad4
color15 #dee3e6

cursor                #dee3e6
cursor_text_color     #0f1416
background            #0f1416
foreground            #dee3e6
selection_foreground  #bfc8cc
selection_background  #40484c
active_border_color   #88d1ec
inactive_border_color #40484c
url_color             #88d1ec

active_tab_foreground   #003543
active_tab_background   #88d1ec
inactive_tab_foreground #bfc8cc
inactive_tab_background #40484c
cursor_trail_color      #bfc8cc
