#!/usr/bin/env bash

declare -A items=(
    [display]="󰍹 Power off monitors"
    [lock]=" Lock"
    [suspend]=" Suspend"
    [reboot]=" Reboot"
    [shutdown]=" Shutdown"
)

selected=$(printf '%s\n' "${items[@]}" | fuzzel --dmenu)

if [[ -n "$selected" ]]; then
    for key in "${!items[@]}"; do
        if [[ "${items[$key]}" == "$selected" ]]; then
            case $key in
            lock)
                swaylock
                ;;
            suspend)
                systemctl suspend
                ;;
            reboot)
                shutdown -r now
                ;;
            shutdown)
                shutdown now
                ;;
            display)
                # TODO: check by env var for compositors
                niri msg action power-off-monitors
                ;;
            esac
            break
        fi
    done
fi
