-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#151218",
  base01 = "#100d12",
  base02 = "#1d1a20",
  base03 = "#4a454e",
  base04 = "#ccc4cf",
  base05 = "#e8e0e8",
  base06 = "#332f35",
  base07 = "#3c383e",

  base08 = "#efa1ac",
  base09 = "#f3b7bf",
  base0A = "#d0c1da",
  base0B = "#d9bafa",
  base0C = "#653b41",
  base0D = "#553b71",
  base0E = "#4d4357",
  base0F = "#b8a1c7",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#553b71',
  fg = '#efdbff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#e87585',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#958e98',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f3b7bf',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#d0c1da',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#6d538b',
})
