[Appearance]
color_scheme_path=/home/jay/.config/qt6ct/colors/rose-pine.conf
custom_palette=true
icon_theme=Papirus
standard_dialogs=default
style=Fusion

[Fonts]
fixed="DejaVu Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Book,0,0"
general="DejaVu Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Book,0,0"

[Interface]
activate_item_on_single_click=0
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=/nix/store/9gk83ym0nf75gic1bhr9zmdsi8ka9h5q-qt6ct-0.11/share/qt6ct/qss/fusion-fixes.qss
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\x61\0\0\x3\xbf\0\0\0\0\0\0\0\0\0\0\x3\x61\0\0\x3\xbf\0\0\0\0\x2\0\0\0\x6@\0\0\0\0\0\0\0\0\0\0\x3\x61\0\0\x3\xbf)

[Troubleshooting]
force_raster_widgets=0
ignored_applications=@Invalid()
