font_family JetBrains Mono
font_size 12
cursor_trail 1
tab_bar_edge top
background_opacity 0.9
background_blur 1

action_alias launch_window launch --cwd current --type os-window
action_alias launch_overlay launch --cwd current --type overlay
map ctrl+g launch_overlay lazygit
map ctrl+n launch_window

include themes/Colors.conf
